"""Proven (DM Code) — anti-counterfeit product authentication platform.

Flask app with two main surfaces:
  * ``/``            customer-facing verification stepper
  * ``/dashboard``   business dashboard for brand management

Security model:
  * Product units are registered with a unique public serial and a secret
    passcode.  Passcodes are stored only as salted PBKDF2-HMAC-SHA256 hashes.
  * Verification uses constant-time comparisons.
  * An immutable, append-only ledger records every scan attempt; the first
    valid scan of a unit "claims" it, later valid scans reveal cloning.
  * Per-IP rate limiting protects the verify and register endpoints.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import os
import secrets
import sqlite3
import time
from collections import defaultdict, deque
from datetime import datetime, timezone
from io import BytesIO

from flask import (
    Flask,
    abort,
    g,
    jsonify,
    redirect,
    render_template,
    request,
    session,
    url_for,
)
from PIL import Image, ImageDraw, ImageFont

# Data Matrix badges are generated by a pure-Python encoder (see the
# "Data Matrix code rendering" section below).  No native libdmtx
# shared library / DLL is needed on any platform.
DMTX_AVAILABLE = True

# --------------------------------------------------------------------------
# Configuration
# --------------------------------------------------------------------------

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
DB_PATH = os.environ.get("PROVEN_DB", os.path.join(BASE_DIR, "proven.db"))

PBKDF2_ITERATIONS = 200_000
RATE_LIMIT_WINDOW = 60.0          # seconds
RATE_LIMIT_MAX_VERIFY = 12        # verify attempts per window / IP
RATE_LIMIT_MAX_REGISTER = 30      # registration attempts per window / IP
MAX_LEDGER_ROWS_PER_UNIT = 500    # sanity cap for display

app = Flask(__name__)
app.config["SECRET_KEY"] = os.environ.get(
    "PROVEN_SECRET_KEY", secrets.token_hex(32)
)
app.config["SESSION_COOKIE_HTTPONLY"] = True
app.config["SESSION_COOKIE_SAMESITE"] = "Lax"


# --------------------------------------------------------------------------
# Database helpers
# --------------------------------------------------------------------------

SCHEMA = """
CREATE TABLE IF NOT EXISTS brands (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    name            TEXT UNIQUE NOT NULL COLLATE NOCASE,
    api_key         TEXT UNIQUE NOT NULL,
    created_utc     TEXT NOT NULL
);

-- Append-only ledger of every successful scan against a genuine unit.
CREATE TABLE IF NOT EXISTS units (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    product_id      INTEGER NOT NULL REFERENCES products(id),
    scanned_utc     TEXT NOT NULL,
    ip              TEXT NOT NULL DEFAULT '',
    user_agent      TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS products (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    brand_id        INTEGER NOT NULL REFERENCES brands(id),
    serial          TEXT UNIQUE NOT NULL COLLATE NOCASE,
    code_hash       TEXT NOT NULL,
    code_salt       TEXT NOT NULL,
    kdf_iters       INTEGER NOT NULL,
    product_name    TEXT NOT NULL,
    description     TEXT NOT NULL DEFAULT '',
    batch           TEXT NOT NULL DEFAULT '',
    issued_utc      TEXT NOT NULL,
    claimed_unit_id INTEGER REFERENCES units(id)
);

-- Every verification attempt (success or failure) is logged for analysis.
CREATE TABLE IF NOT EXISTS scan_log (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    serial      TEXT NOT NULL,
    outcome     TEXT NOT NULL,
    brand_id    INTEGER REFERENCES brands(id),
    scanned_utc TEXT NOT NULL,
    ip          TEXT NOT NULL DEFAULT ''
);

CREATE INDEX IF NOT EXISTS idx_units_product ON units(product_id);
CREATE INDEX IF NOT EXISTS idx_scanlog_brand ON scan_log(brand_id);
"""


def get_db() -> sqlite3.Connection:
    db = getattr(g, "_database", None)
    if db is None:
        db = g._database = sqlite3.connect(DB_PATH)
        db.row_factory = sqlite3.Row
        db.execute("PRAGMA foreign_keys = ON")
    return db


@app.teardown_appcontext
def close_db(_exc):
    db = getattr(g, "_database", None)
    if db is not None:
        db.close()


def init_db():
    con = sqlite3.connect(DB_PATH)
    con.executescript(SCHEMA)
    con.commit()
    con.close()


def utcnow_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


# --------------------------------------------------------------------------
# Cryptography: salted PBKDF2-HMAC-SHA256 + constant-time comparison
# --------------------------------------------------------------------------


def hash_passcode(passcode: str, *, salt: bytes | None = None,
                  iterations: int = PBKDF2_ITERATIONS) -> tuple[str, str, int]:
    """Return (hash_hex, salt_hex, iterations) for a secret passcode."""
    if salt is None:
        salt = secrets.token_bytes(16)
    dk = hashlib.pbkdf2_hmac(
        "sha256", passcode.encode("utf-8"), salt, iterations
    )
    return dk.hex(), salt.hex(), iterations


def verify_passcode(passcode: str, code_hash: str, salt_hex: str,
                    iterations: int) -> bool:
    """Constant-time check of a passcode against its stored digest."""
    try:
        salt = bytes.fromhex(salt_hex)
    except ValueError:
        return False
    dk = hashlib.pbkdf2_hmac(
        "sha256", passcode.encode("utf-8"), salt, iterations
    )
    return hmac.compare_digest(dk.hex(), code_hash.lower())


def new_api_key() -> str:
    return "prv_" + secrets.token_hex(24)


def normalize_serial(raw: str) -> str:
    """Serials are case-insensitive alphanumerics/dashes, max 64 chars."""
    s = "".join((raw or "").split()).upper()
    allowed = set("ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_")
    if not (6 <= len(s) <= 64):
        return ""
    if not all(ch in allowed for ch in s):
        return ""
    return s


# --------------------------------------------------------------------------
# Per-IP rate limiting (sliding-window, in-process token bucket)
# --------------------------------------------------------------------------

_rate_buckets: dict[tuple[str, str], deque] = defaultdict(deque)


def client_ip() -> str:
    fwd = request.headers.get("X-Forwarded-For", "")
    if fwd:
        return fwd.split(",")[0].strip()
    return request.remote_addr or "unknown"


def rate_limited(endpoint: str) -> bool:
    """True when the caller exceeded the budget for this endpoint."""
    limit = (RATE_LIMIT_MAX_VERIFY if endpoint == "verify"
             else RATE_LIMIT_MAX_REGISTER)
    key = (endpoint, client_ip())
    now = time.monotonic()
    bucket = _rate_buckets[key]
    while bucket and now - bucket[0] > RATE_LIMIT_WINDOW:
        bucket.popleft()
    if len(bucket) >= limit:
        return True
    bucket.append(now)
    return False


def rate_limit_response(endpoint: str):
    resp = jsonify({
        "ok": False,
        "error": "rate_limited",
        "message": ("Too many requests from this device. Please wait a "
                    "minute and try again."),
    })
    resp.status_code = 429
    resp.headers["Retry-After"] = str(int(RATE_LIMIT_WINDOW))
    return resp


# --------------------------------------------------------------------------
# Data Matrix code rendering — pure-Python ECC200 encoder (ISO/IEC 16022)
#
# Written from scratch on top of Pillow only.  It deliberately avoids the
# native libdmtx shared library / DLL that pylibdmtx wraps, so scannable
# badges work on every platform after ``pip install -r requirements.txt``.
# --------------------------------------------------------------------------

CODE_BASE_URL = os.environ.get("PROVEN_PUBLIC_URL", "").rstrip("/")


def build_payload(serial: str, passcode: str) -> str:
    """The payload embedded in the physical DM code on the product."""
    base = CODE_BASE_URL or request.url_root.rstrip("/")
    return f"{base}/verify?serial={serial}&key={passcode}"


class _GF256:
    """Galois field GF(256) arithmetic for DM Reed-Solomon codewords."""

    def __init__(self, primitive_poly: int = 0x12D):
        self.exp = [0] * 512
        self.log = [0] * 256
        x = 1
        for i in range(255):
            self.exp[i] = x
            self.log[x] = i
            x <<= 1
            if x & 0x100:
                x ^= primitive_poly
        assert x == 1, "primitive polynomial must generate GF(256)"
        for i in range(255, 512):
            self.exp[i] = self.exp[i - 255]

    def mul(self, a: int, b: int) -> int:
        if a == 0 or b == 0:
            return 0
        return self.exp[self.log[a] + self.log[b]]


_GF = _GF256()


def _rs_generator_poly(degree: int) -> list[int]:
    """Reed-Solomon generator polynomial over GF(256), highest power first."""
    g = [1]
    for i in range(degree):
        g.append(0)
        for j in range(len(g) - 1):
            g[j] = _GF.mul(g[j], _GF.exp[i]) ^ g[j + 1]
        del g[-1]
    return g


def _rs_encode(data: bytes, cw_count: int) -> list[int]:
    """Compute ``cw_count`` Reed-Solomon error-correction codewords.

    The generator polynomial has degree ``cw_count`` (``cw_count + 1``
    coefficients); the remainder of the synthetic division is returned.
    """
    gen = _rs_generator_poly(cw_count)
    result = list(data) + [0] * cw_count
    for i in range(len(data)):
        coeff = result[i]
        if coeff:
            for j in range(len(gen)):
                result[i + j] = _GF.mul(gen[j], coeff) ^ result[i + j + 1]
    return result[len(data):]


# Symbol geometry per ISO/IEC 16022 Table 1 (ECC200 square symbols).
# Each row: symbol size name, total codewords (data + ECC), number of
# ECC codewords, the *per-block* mapping dimensions, and the block grid.
# Symbols larger than 26x26 are split into 2x2 / 4x4 / 6x6 blocks, so
# the mapping matrix is smaller than the symbol itself — the block
# count below must match the standard exactly, otherwise capacity is
# silently wrong (that is what produced the old "mapping too small"
# AssertionError for payloads past ~37 characters).
#   name -> (total cw, ecc cw, block rows, block cols, nr, nc)
_DM_SIZES: dict[str, tuple[int, int, int, int, int, int]] = {
    "10x10":   (3,    5,    8,   8,  1, 1),
    "12x12":   (5,    7,   10,  10,  1, 1),
    "14x14":   (8,    10,  12,  12,  1, 1),
    "16x16":   (12,   12,  14,  14,  1, 1),
    "18x18":   (18,   14,  16,  16,  1, 1),
    "20x20":   (22,   18,  18,  18,  1, 1),
    "22x22":   (30,   20,  20,  20,  1, 1),
    "24x24":   (36,   24,  22,  22,  1, 1),
    "26x26":   (44,   28,  24,  24,  1, 1),
    "32x32":   (62,   36,  14,  14,  2, 2),
    "36x36":   (84,   42,  16,  16,  2, 2),
    "40x40":   (106,  48,  18,  18,  2, 2),
    "44x44":   (122,  56,  20,  20,  2, 2),
    "48x48":   (152,  68,  22,  22,  2, 2),
    "52x52":   (180,  76,  14,  14,  4, 4),
    "64x64":   (213,  88,  14,  14,  4, 4),
    "72x72":   (261,  100, 16,  16,  4, 4),
    "80x80":   (322,  120, 18,  18,  4, 4),
    "88x88":   (376,  132, 20,  20,  4, 4),
    "96x96":   (436,  144, 22,  22,  4, 4),
    "104x104": (512,  172, 24,  24,  4, 4),
    "120x120": (620,  192, 14,  14,  6, 6),
    "132x132": (744,  224, 16,  16,  6, 6),
    "144x144": (896,  256, 18,  18,  6, 6),
    "160x160": (1240, 304, 20,  20,  6, 6),
    "176x176": (1476, 352, 22,  22,  6, 6),
    "192x192": (1812, 384, 24,  24,  6, 6),
}

# Data-region geometry derived from the table above:
#   name -> (total cw, ecc cw, mapping rows, mapping cols,
#            data cw, num blocks)
_DM_GEOM: dict[str, tuple[int, int, int, int, int, int]] = {}
for _n, (_tot, _ecc, _br, _bc, _nr, _nc) in _DM_SIZES.items():
    _mr, _mc = _br * _nr, _bc * _nc
    _blocks = _nr * _nc
    assert _mr * _mc >= _tot * 8, f"{_n}: mapping too small for {_tot} cw"
    _DM_GEOM[_n] = (_tot, _ecc, _mr, _mc, _tot - _ecc, _blocks)

_DM_ORDER = sorted(_DM_GEOM, key=lambda n: _DM_GEOM[n][0])


def _dm_ascii_codewords(text: str) -> list[int]:
    """ASCII encodation (high-level): plain values 1..128, digit pairs
    compressed to 2..104; never emits codes 201..231, so no latch shifts."""
    raw = text.encode("utf-8")
    words: list[int] = []
    i = 0
    while i < len(raw):
        ch = raw[i]
        nxt = raw[i + 1] if i + 1 < len(raw) else None
        if (ch is not None and nxt is not None
                and 48 <= ch <= 57 and 48 <= nxt <= 57):
            words.append((nxt - 48) + 10 * (ch - 48) + 130)
            i += 2
        else:
            words.append(ch + 1)
            i += 1
    return words


def _dm_random_bit(row: int, col: int, height: int, width: int) -> bool:
    """Pseudo-random module pattern for unused padding positions
    (ISO/IEC 16022 Annex X)."""
    r, c = row + 1, col + 1
    tmp = ((r * c) % 7) + 2 * r * c + height * width
    if (tmp % 3) == 0:
        return False
    return ((tmp - 1) % 3) == 0


def _dm_module_positions(rows: int, cols: int) -> list[tuple[int, int]]:
    """Mapping-matrix traversal order (ISO/IEC 16022 Annex D).

    Returns one (row, col) per module-bit in codeword order, MSB first —
    exactly ``rows*cols`` positions, each used once.  Implements the
    classic diagonal "streak" walk plus the four corner cases that wrap
    around symbol edges.  All coordinates are taken modulo the mapping
    matrix, matching the reference implementation ("utah" placement).
    """
    grid = [[False] * cols for _ in range(rows)]
    order: list[tuple[int, int]] = []

    def row_sub(i):
        return (i + rows) % rows

    def col_sub(j):
        return (j + cols) % cols

    def put(r, c):
        if not grid[r][c]:
            grid[r][c] = True
            order.append((r, c))

    def corner1():
        # (r-1+R, c-1), (r-1+R, c), (R, c), (R, c+1), (R, c+2),
        # (r, c+2-C), (r+1, c+2-C), (r+2, c+2-C)   with r=R-1, c=0
        put(row_sub(rows - 2), col_sub(cols - 1))
        put(row_sub(rows - 2), 0)
        put(row_sub(rows - 1), 0)
        put(0, 1)
        put(0, 2)
        put(1, cols - 2)
        put(2, cols - 2)
        put(3, cols - 2)

    def corner2():
        # r=0, c=C-4
        put(row_sub(rows - 1), 0)
        put(row_sub(rows - 1), col_sub(cols - 1))
        put(0, col_sub(cols - 3))
        put(0, col_sub(cols - 2))
        put(0, col_sub(cols - 1))
        put(1, col_sub(cols - 3))
        put(1, col_sub(cols - 2))
        put(1, col_sub(cols - 1))

    def corner3():
        # r=R-1, c=2, R%8==0, C==8
        put(row_sub(rows - 1), 0)
        put(row_sub(rows - 1), col_sub(cols - 1))
        put(0, col_sub(cols - 3))
        put(0, col_sub(cols - 2))
        put(0, col_sub(cols - 1))
        put(1, col_sub(cols - 3))
        put(1, col_sub(cols - 2))
        put(1, col_sub(cols - 1))

    def corner4():
        # r=R-3, c=0, R%8==0, C==8
        put(row_sub(rows - 3), 0)
        put(row_sub(rows - 2), 0)
        put(row_sub(rows - 1), 0)
        put(row_sub(rows - 1), 1)
        put(row_sub(rows - 1), 2)
        put(0, col_sub(cols - 4))
        put(0, col_sub(cols - 3))
        put(0, col_sub(cols - 2))

    def utah(r, c):
        """Standard 'utah' stamp of 8 bits anchored at (r, c)."""
        put(row_sub(r - 1), col_sub(c + 1))
        put(row_sub(r - 1), col_sub(c + 2))
        put(row_sub(r), col_sub(c + 2))
        put(row_sub(r + 1), col_sub(c + 2))
        put(row_sub(r + 2), col_sub(c + 1))
        put(row_sub(r + 2), col_sub(c))
        put(row_sub(r + 3), col_sub(c))
        put(row_sub(r + 4), col_sub(c))

    def place(r, c):
        if r == rows - 1 and c == 0:                       # corner case 1
            corner1()
        elif r == rows - 1 and c == 2 and rows % 8 == 0 and cols == 8:
            corner3()                                       # corner case 3
        elif r == rows - 3 and c == 0 and rows % 8 == 0 and cols == 8:
            corner4()                                       # corner case 4
        elif r == 0 and c == cols - 4:                      # corner case 2
            corner2()
        else:
            utah(r, c)

    def undamaged(r, c):
        return not (grid[row_sub(r + 2)][col_sub(c - 1)]
                    or grid[row_sub(r + 2)][c]
                    or grid[row_sub(r + 2)][col_sub(c + 1)]
                    or grid[r][col_sub(c - 1)])

    # --- main sweep over the interior triangular region -----------------
    row, col = 4, 0
    while row < rows and col < cols:
        if undamaged(row, col):
            r, c = row, col
            i = 0
            while r >= 0 and c < cols and not grid[r][c]:
                place(r, c)
                i += 1
                r -= 1
                c += 2
                r, c = row_sub(rows - i), col_sub(2 * i)
        row, col = row + 2, col + 2

    # --- bottom-left triangle --------------------------------------------
    row, col = rows - 1, 1
    while col < cols and not grid[rows - 1][col]:
        if undamaged(row, col):
            r, c = row, col
            i = 0
            while r < rows and c < cols and not grid[r][c]:
                place(r, c)
                i += 1
                r += 1
                c += 2
                r, c = row_sub((rows - 1 + i) % rows), col_sub(2 * i)
        row, col = row - 2, col + 2

    assert len(order) == rows * cols, \
        f"mapping produced {len(order)} of {rows * cols} positions"
    return order


def _dm_pad_word(n: int) -> int:
    """Standard pad codeword for position ``n`` (0-based) — §5.2.4."""
    if n == 0:
        return 129
    return ((129 + ((((n + 1) * 254) % 253) + 1)) % 254) + 1


def _interleave(data: bytes, ncw: int, ecc_count: int,
                num_blocks: int) -> list[int]:
    """Build the final codeword sequence for multi-block symbols.

    ISO/IEC 16022 §5.9: the data is split into ``num_blocks`` blocks;
    each block holds ``k_hi = ncw // num_blocks`` data codewords, and if
    there is a remainder ``r = ncw % num_blocks`` then *block r* (0-based
    — not the last one!) holds one fewer word (e.g. 64x64: 125 cw per
    block, 88 ECC in 16 blocks of 22 ECC words, so block 7 carries only
    36 data words).  The encoder interleaves by codeword index across
    blocks: d[0][0], d[1][0], …, skipping short positions; likewise for
    the ECC codewords.

    ``data`` may be shorter than the block size allows when an EDIFACT /
    C40 / base-256 segment was terminated with an unpad "latch" codeword
    (§5.4.4); those trailing slots are filled with pad codewords first.
    """
    n = len(data)
    k_hi = ncw // num_blocks            # data cw in most blocks
    r = ncw % num_blocks                # short block index (or none)
    if k_hi == 0:
        raise ValueError("invalid block split")
    if n < ncw:                         # complete to capacity with pads
        data = data + bytes(_dm_pad_word(i) for i in range(n, ncw))
        n = ncw

    blocks_data: list[list[int]] = []
    pos = 0
    for b in range(num_blocks):
        size = k_hi - (1 if b == r else 0)
        blocks_data.append(list(data[pos:pos + size]))
        pos += size
    assert pos == n

    ecc_per_block = [ecc_count // num_blocks] * num_blocks
    for b in range(ecc_count % num_blocks):
        ecc_per_block[b] += 1
    blocks_ecc = [_rs_encode(bytes(blk), e)
                  for blk, e in zip(blocks_data, ecc_per_block)]

    out: list[int] = []
    for i in range(k_hi):               # longest data block length
        for b in range(num_blocks):
            if i < len(blocks_data[b]):
                out.append(blocks_data[b][i])
    max_e = max(ecc_per_block)
    for i in range(max_e):
        for b in range(num_blocks):
            if i < len(blocks_ecc[b]):
                out.append(blocks_ecc[b][i])
    return out


def encode_datamatrix(text: str) -> Image.Image:
    """Encode ASCII text into a 1-bit Data Matrix ECC200 symbol image."""
    words = _dm_ascii_codewords(text)
    chosen = None
    for name in _DM_ORDER:
        if len(words) <= _DM_GEOM[name][4]:      # data codeword capacity
            chosen = name
            break
    if chosen is None:
        raise ValueError("payload too large for supported DM sizes")
    total, ecc, mrows, mcols, ncw, nb = _DM_GEOM[chosen]

    # Pad with the standard pseudo-random sequence (254 / 129 style).
    while len(words) < ncw:
        words.append(_dm_pad_word(len(words)))
    data_bytes = bytes(words[:ncw])
    codewords = _interleave(data_bytes, ncw, ecc, nb)
    assert len(codewords) == total

    bits = iter([((w >> b) & 1) != 0 for w in codewords for b in
                 range(7, -1, -1)])
    grid = [[False] * mcols for _ in range(mrows)]
    positions = _dm_module_positions(mrows, mcols)
    for (r, c), b in zip(positions, bits):
        grid[r][c] = b
    # Any leftover positions (larger mapping than codeword bits require)
    # get the pseudo-random fill pattern.
    filled = set(positions[:len(codewords) * 8])
    for r in range(mrows):
        for c in range(mcols):
            if (r, c) not in filled:
                grid[r][c] = _dm_random_bit(r, c, mrows, mcols)

    # Block layout comes from the size table itself (ISO/IEC 16022
    # Table 1): 1x1 up to 26x26, then 2x2, 4x4, 6x6 and 8x8 blocks.
    nrb = int(nb ** 0.5)
    ncb = nrb
    assert nrb * ncb == nb, f"{chosen}: non-square block layout"
    height = nrb * mrows + 2 * nrb
    width = ncb * mcols + 2 * ncb
    symbol = [[False] * width for _ in range(height)]

    # Clock patterns: bottom row solid, left column solid, top row and
    # right column alternating — repeated for every row/column block.
    for blk_r in range(nrb):
        top = blk_r * (mrows + 2)
        bottom = top + mrows + 1
        for c in range(width):
            symbol[top][c] = (c % 2) == 0          # alternating top
            symbol[bottom][c] = True               # solid bottom
    for blk_c in range(ncb):
        left = blk_c * (mcols + 2)
        right = left + mcols + 1
        for r in range(height):
            symbol[r][left] = True                 # solid left
            symbol[r][right] = (r % 2) == 0        # alternating right

    # Place the data blocks inside their clock frames.
    bh, bw = mrows // nrb, mcols // ncb
    for br in range(nrb):
        for bc in range(ncb):
            base_r = br * (mrows + 2) + 1
            base_c = bc * (mcols + 2) + 1
            for r in range(bh):
                for c in range(bw):
                    symbol[base_r + r][base_c + c] = \
                        grid[br * bh + r][bc * bw + c]

    img = Image.new("1", (width + 4, height + 4), 1)   # white quiet zone
    px = img.load()
    for r in range(height):
        for c in range(width):
            if symbol[r][c]:
                px[c + 2, r + 2] = 0
    return img


# Font candidates across platforms (Linux / Windows / macOS).  PIL also
# accepts bare family names like "arialbd.ttf" which it resolves through
# the Windows font registry (HKLM SOFTWARE\Microsoft\Windows NT\CurrentVersion\Fonts).
_FONT_CANDIDATES = (
    # Windows
    "arialbd.ttf",
    r"C:\Windows\Fonts\arialbd.ttf",
    r"C:\Windows\Fonts\segoeuib.ttf",
    r"C:\Windows\Fonts\calibrib.ttf",
    # Linux
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf",
    # macOS
    "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
    "/Library/Fonts/Arial Bold.ttf",
)


def _load_badge_font(size: int = 16):
    for path in _FONT_CANDIDATES:
        try:
            return ImageFont.truetype(path, size)
        except OSError:
            continue
    return ImageFont.load_default()


def render_dm_badge(payload: str) -> Image.Image:
    """Render a Data Matrix symbol inside a QR-style rounded badge.

    Uses the pure-Python ECC200 encoder above — no native libdmtx
    shared library / DLL is involved, so the badge is scannable on
    every platform straight after ``pip install -r requirements.txt``.
    """
    # Pick the smallest square DM size that fits the payload, then upscale.
    symbol = encode_datamatrix(payload)

    scale = max(3, 240 // symbol.width)
    sym = symbol.resize((symbol.width * scale, symbol.height * scale),
                        Image.NEAREST)
    pad = 26
    side = sym.width + pad * 2
    badge = Image.new("RGB", (side, side + 34), "#ffffff")
    draw = ImageDraw.Draw(badge)

    # Rounded frame resembling a QR container.
    r = 18
    draw.rounded_rectangle([1, 1, side - 2, side + 32], radius=r,
                           outline="#123c2e", width=4)
    badge.paste(sym, (pad, pad))

    label = "PROVEN · DM CODE"
    font = _load_badge_font(16)
    tw = draw.textlength(label, font=font)
    draw.text(((side - tw) / 2, side + 4), label, font=font, fill="#123c2e")
    return badge


def badge_to_data_uri(img: Image.Image) -> str:
    buf = BytesIO()
    img.save(buf, format="PNG")
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()


# --------------------------------------------------------------------------
# Core authentication logic
# --------------------------------------------------------------------------


def lookup_product(db: sqlite3.Connection, serial: str):
    return db.execute(
        "SELECT p.*, b.name AS brand_name FROM products p "
        "JOIN brands b ON b.id = p.brand_id WHERE p.serial = ?",
        (serial,),
    ).fetchone()


def scan_result(db: sqlite3.Connection, serial: str, passcode: str) -> dict:
    """Classify a scan into one of the ledger outcomes.

    Outcomes:
      * genuine_first_use — valid code, never seen before → claims unit
      * genuine_cloned    — valid code already claimed by another scan
      * unknown_serial    — serial not in the registry (counterfeit print)
      * bad_passcode      — serial exists but secret does not match

    Every attempt is appended to ``scan_log`` for brand analysis; only
    successful scans are appended to the immutable ownership ledger
    (``units``).
    """
    product = lookup_product(db, serial)
    if product is None:
        outcome = "unknown_serial"
    elif not verify_passcode(passcode, product["code_hash"],
                             product["code_salt"], product["kdf_iters"]):
        outcome = "bad_passcode"
    else:
        # Valid credentials → append to the immutable ledger.
        claimed = product["claimed_unit_id"]
        if claimed is None:
            cur = db.execute(
                "INSERT INTO units (product_id, scanned_utc, ip, user_agent) "
                "VALUES (?, ?, ?, ?)",
                (product["id"], utcnow_iso(), client_ip(),
                 request.headers.get("User-Agent", "")[:200]),
            )
            unit_id = cur.lastrowid
            # First valid scan wins; guarded UPDATE avoids double-claim races.
            upd = db.execute(
                "UPDATE products SET claimed_unit_id = ? "
                "WHERE id = ? AND claimed_unit_id IS NULL",
                (unit_id, product["id"]),
            )
            if upd.rowcount == 1:
                outcome = "genuine_first_use"
            else:
                db.execute("DELETE FROM units WHERE id = ?", (unit_id,))
                outcome = "genuine_cloned"
        else:
            db.execute(
                "INSERT INTO units (product_id, scanned_utc, ip, user_agent) "
                "VALUES (?, ?, ?, ?)",
                (product["id"], utcnow_iso(), client_ip(),
                 request.headers.get("User-Agent", "")[:200]),
            )
            outcome = "genuine_cloned"

    db.execute(
        "INSERT INTO scan_log (serial, outcome, brand_id, scanned_utc, ip) "
        "VALUES (?, ?, ?, ?, ?)",
        (serial, outcome,
         product["brand_id"] if product else None,
         utcnow_iso(), client_ip()),
    )
    db.commit()

    res = {"outcome": outcome, "product": product}
    if product is not None:
        res["scan_count"] = db.execute(
            "SELECT COUNT(*) c FROM units WHERE product_id = ?",
            (product["id"],),
        ).fetchone()["c"]
    return res


OUTCOME_COPY = {
    "genuine_first_use": {
        "title": "Genuine — first verified use",
        "verdict": "GENUINE",
        "tone": "good",
        "blurb": ("This is an authentic {brand} item. Your scan has "
                  "registered it as the first legitimate owner."),
    },
    "genuine_cloned": {
        "title": "Genuine code — but already claimed",
        "verdict": "POSSIBLE CLONE",
        "tone": "warn",
        "blurb": ("The security code is authentic, however this exact code "
                  "was already verified {prior} time(s). You may have been "
                  "sold a cloned or second-hand item — contact {brand}."),
    },
    "unknown_serial": {
        "title": "Serial not found",
        "verdict": "COUNTERFEIT",
        "tone": "bad",
        "blurb": ("This serial does not exist in the {brand} registry. The "
                  "label was most likely fabricated. Do not consume or use "
                  "this product."),
    },
    "bad_passcode": {
        "title": "Secret mismatch",
        "verdict": "COUNTERFEIT",
        "tone": "bad",
        "blurb": ("The serial exists, but the hidden security key does not "
                  "match. Counterfeiters often copy visible serials without "
                  "the secret. Treat this product as fake."),
    },
}


# --------------------------------------------------------------------------
# Session / auth helpers for the dashboard
# --------------------------------------------------------------------------


def current_brand():
    bid = session.get("brand_id")
    if bid is None:
        return None
    return get_db().execute(
        "SELECT * FROM brands WHERE id = ?", (bid,)
    ).fetchone()


def require_brand():
    brand = current_brand()
    if brand is None:
        return None
    return brand


# --------------------------------------------------------------------------
# Routes — customer facing
# --------------------------------------------------------------------------


def _render_verify_page():
    """Render the customer-facing scan/verification stepper."""
    serial = (request.args.get("serial") or "").strip().upper()
    key = (request.args.get("key") or "").strip()
    return render_template("verify.html", prefill_serial=serial,
                           prefill_key=key, auto=bool(serial and key))


@app.route("/")
def index():
    """Home page is the scan/verify page — never the brand login page."""
    return _render_verify_page()


@app.route("/verify", methods=["GET"])
def verify_page():
    """Deep link target of the DM code: prefills and auto-runs the stepper."""
    return _render_verify_page()


@app.route("/api/verify", methods=["POST"])
def api_verify():
    if rate_limited("verify"):
        return rate_limit_response("verify")

    data = request.get_json(silent=True) or {}
    serial = normalize_serial(data.get("serial", ""))
    passcode = (data.get("passcode") or "").strip()

    if not serial or not passcode:
        return jsonify({"ok": False, "error": "missing_fields",
                        "message": "Both serial and security key "
                                   "are required."}), 400

    db = get_db()
    res = scan_result(db, serial, passcode)
    product = res["product"]
    outcome = res["outcome"]
    copy = OUTCOME_COPY[outcome]
    brand_name = product["brand_name"] if product else "the manufacturer"

    prior = max(res.get("scan_count", 1) - 1, 0)
    payload = {
        "ok": True,
        "outcome": outcome,
        "verdict": copy["verdict"],
        "tone": copy["tone"],
        "title": copy["title"],
        "message": copy["blurb"].format(brand=brand_name, prior=prior),
    }
    if product:
        payload.update({
            "product_name": product["product_name"],
            "brand": brand_name,
            "batch": product["batch"],
            "issued_utc": product["issued_utc"],
            "scan_count": res.get("scan_count"),
        })
    status = 200 if outcome.startswith("genuine") else 404 \
        if outcome == "unknown_serial" else 403
    return jsonify(payload), status


# --------------------------------------------------------------------------
# Routes — business dashboard
# --------------------------------------------------------------------------


@app.route("/dashboard")
def dashboard():
    brand = require_brand()
    if brand is None:
        return redirect(url_for("login"))
    db = get_db()
    products = db.execute(
        """
        SELECT p.*,
               (SELECT COUNT(*) FROM units u WHERE u.product_id = p.id)
                 AS scan_count,
               (SELECT MAX(scanned_utc) FROM units u
                 WHERE u.product_id = p.id) AS last_scan
        FROM products p WHERE p.brand_id = ? ORDER BY p.id DESC
        """,
        (brand["id"],),
    ).fetchall()

    stats = {
        "products": len(products),
        "scans": sum(p["scan_count"] for p in products),
        "first_uses": sum(1 for p in products if p["claimed_unit_id"]),
        "clone_alerts": sum(1 for p in products
                            if p["claimed_unit_id"] and p["scan_count"] > 1),
    }

    # Attempt analytics from the append-only scan log (includes failed
    # attempts such as counterfeit serials probing this brand's formats).
    outcome_rows = db.execute(
        "SELECT outcome, COUNT(*) c FROM scan_log WHERE brand_id = ? "
        "GROUP BY outcome",
        (brand["id"],),
    ).fetchall()
    stats["outcomes"] = {r["outcome"]: r["c"] for r in outcome_rows}
    stats["fake_attempts"] = sum(
        c for o, c in stats["outcomes"].items()
        if o in ("bad_passcode",)
    ) + db.execute(
        "SELECT COUNT(*) c FROM scan_log "
        "WHERE brand_id IS NULL AND outcome = 'unknown_serial'"
    ).fetchone()["c"]

    recent = db.execute(
        "SELECT * FROM scan_log WHERE brand_id = ? OR brand_id IS NULL "
        "ORDER BY id DESC LIMIT 15",
        (brand["id"],),
    ).fetchall()

    alerts = [p for p in products
              if p["claimed_unit_id"] and p["scan_count"] > 1]
    return render_template("dashboard.html", brand=brand,
                           products=products, stats=stats, alerts=alerts,
                           recent=recent)


@app.route("/login", methods=["GET", "POST"])
def login():
    error = None
    if request.method == "POST":
        name = (request.form.get("brand_name") or "").strip()
        key = (request.form.get("api_key") or "").strip()
        db = get_db()
        brand = db.execute(
            "SELECT * FROM brands WHERE name = ? COLLATE NOCASE",
            (name,),
        ).fetchone()
        if brand and hmac.compare_digest(brand["api_key"], key):
            session["brand_id"] = brand["id"]
            session.permanent = False
            return redirect(url_for("dashboard"))
        error = "Unknown brand or incorrect API key."
    return render_template("login.html", error=error)


@app.route("/logout", methods=["POST"])
def logout():
    session.clear()
    return redirect(url_for("login"))


@app.route("/register-brand", methods=["POST"])
def register_brand():
    if rate_limited("register"):
        return rate_limit_response("register")
    name = (request.form.get("brand_name") or "").strip()
    if not (2 <= len(name) <= 60):
        return render_template(
            "login.html",
            error="Brand name must be 2–60 characters."), 400
    db = get_db()
    api_key = new_api_key()
    try:
        cur = db.execute(
            "INSERT INTO brands (name, api_key, created_utc) "
            "VALUES (?, ?, ?)",
            (name, api_key, utcnow_iso()),
        )
        db.commit()
    except sqlite3.IntegrityError:
        return render_template(
            "login.html",
            error=f"A brand named “{name}” already exists."), 409
    session["brand_id"] = cur.lastrowid
    # The freshly minted API key is revealed exactly once on the login page;
    # the brand is already signed in, but we show it so they can save it.
    return render_template(
        "login.html", error=None,
        new_brand_name=name, new_api_key=api_key)


@app.route("/api/products", methods=["POST"])
def api_create_product():
    """Register a genuine product unit: serial + secret passcode."""
    brand = current_brand()
    if brand is None:
        return jsonify({"ok": False, "error": "unauthorized"}), 401
    if rate_limited("register"):
        return rate_limit_response("register")

    data = request.get_json(silent=True) or {}
    serial = normalize_serial(data.get("serial", ""))
    passcode = (data.get("passcode") or "").strip()
    pname = (data.get("product_name") or "").strip()[:120]
    batch = (data.get("batch") or "").strip()[:60]
    description = (data.get("description") or "").strip()[:500]

    errors = []
    if not serial:
        errors.append("Serial must be 6–64 chars of A–Z 0–9 - _")
    if len(passcode) < 8:
        errors.append("Passcode must be at least 8 characters")
    if not pname:
        errors.append("Product name is required")
    if errors:
        return jsonify({"ok": False, "error": "validation",
                        "messages": errors}), 400

    code_hash, salt, iters = hash_passcode(passcode)
    db = get_db()
    try:
        cur = db.execute(
            "INSERT INTO products (brand_id, serial, code_hash, code_salt, "
            "kdf_iters, product_name, description, batch, issued_utc) "
            "VALUES (?,?,?,?,?,?,?,?,?)",
            (brand["id"], serial, code_hash, salt, iters, pname,
             description, batch, utcnow_iso()),
        )
        db.commit()
    except sqlite3.IntegrityError:
        return jsonify({"ok": False, "error": "duplicate",
                        "message": f"Serial {serial} is already "
                                    "registered."}), 409

    pid = cur.lastrowid
    payload = build_payload(serial, passcode)
    badge = render_dm_badge(payload)
    png_b64 = badge_to_data_uri(badge)[len("data:image/png;base64,"):]
    return jsonify({
        "ok": True,
        "product_id": pid,
        "serial": serial,
        "payload": payload,
        # Shown exactly once so the brand can print the scratch panel.
        "passcode_shown_once": passcode,
        "png_base64": png_b64,
    })


@app.route("/products/<serial>/ledger")
def product_ledger(serial):
    brand = require_brand()
    if brand is None:
        return redirect(url_for("login"))
    db = get_db()
    product = db.execute(
        "SELECT p.*, b.name AS brand_name FROM products p "
        "JOIN brands b ON b.id = p.brand_id "
        "WHERE p.serial = ? AND p.brand_id = ?",
        (normalize_serial(serial), brand["id"]),
    ).fetchone()
    if product is None:
        abort(404)
    entries = db.execute(
        "SELECT * FROM units WHERE product_id = ? "
        "ORDER BY id ASC LIMIT ?",
        (product["id"], MAX_LEDGER_ROWS_PER_UNIT),
    ).fetchall()
    return render_template("ledger.html", brand=brand, product=product,
                           entries=entries)


@app.route("/healthz")
def healthz():
    return jsonify({"ok": True, "time": utcnow_iso()})


# --------------------------------------------------------------------------
# Bootstrap
# --------------------------------------------------------------------------

init_db()

if __name__ == "__main__":
    # Windows console fonts (legacy cp codepages) can't render the Unicode
    # middot in banner text; force UTF-8 output when possible.
    if os.name == "nt":
        try:
            os.system("chcp 65001 >nul 2>nul")
        except Exception:
            pass

    port = int(os.environ.get("PORT", 5000))
    print(f"Proven (DM Code) running on http://localhost:{port}/")
    if not DMTX_AVAILABLE:
        print("WARNING: libdmtx native library not found — DM badges will "
              "use a placeholder image.")
        print("See README.md for installation instructions.")
    app.run(host="0.0.0.0", port=port,
            debug=bool(os.environ.get("FLASK_DEBUG")))
